### ISSUE TITLE
Failure to build pf4j : Tests failure

### ISSUE THREAD

**Issue by bigk-fr** [decebals/pf4j#120]
Hi

I have a problem building pf4j using your instructions on ubuntu 16.04 using :
`$ git clone https://github.com/decebals/pf4j.git`
`$ cd pf4j`
`$ mvn clean package`

here is the output of maven :
```
[INFO] Scanning for projects...
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for ro.fortsoft.pf4j.demo:pf4j-demo-plugin1:jar:1.2.0-SNAPSHOT
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] The expression ${packaging} is deprecated. Please use ${project.packaging} instead.
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for ro.fortsoft.pf4j.demo:pf4j-demo-plugin2:jar:1.2.0-SNAPSHOT
[WARNING] The expression ${artifactId} is deprecated. Please use ${project.artifactId} instead.
[WARNING] The expression ${version} is deprecated. Please use ${project.version} instead.
[WARNING] The expression ${packaging} is deprecated. Please use ${project.packaging} instead.
[WARNING] 
[WARNING] It is highly recommended to fix these problems because they threaten the stability of your build.
[WARNING] 
[WARNING] For this reason, future Maven versions might no longer support building such malformed projects.
[WARNING] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] PF4J Parent
[INFO] PF4J
[INFO] Demo Parent
[INFO] Demo Api
[INFO] Demo App
[INFO] Demo Plugins Parent
[INFO] Demo Plugin #1
[INFO] Demo Plugin #2
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building PF4J Parent 1.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pf4j-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ pf4j-parent ---
[INFO] 
[INFO] --- maven-javadoc-plugin:2.8:jar (default) @ pf4j-parent ---
[INFO] Not executing Javadoc as the project is not a Java classpath-capable package
[INFO] 
[INFO] >>> maven-source-plugin:2.2:jar (default) > generate-sources @ pf4j-parent >>>
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ pf4j-parent ---
[INFO] 
[INFO] <<< maven-source-plugin:2.2:jar (default) < generate-sources @ pf4j-parent <<<
[INFO] 
[INFO] --- maven-source-plugin:2.2:jar (default) @ pf4j-parent ---
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building PF4J 1.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ pf4j ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.0:enforce (enforce-maven) @ pf4j ---
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:resources (default-resources) @ pf4j ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:compile (default-compile) @ pf4j ---
[INFO] Compiling 57 source files to /home/ocau/tmp/pf4j/pf4j/target/classes
[INFO] 
[INFO] --- maven-resources-plugin:2.4.3:testResources (default-testResources) @ pf4j ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ocau/tmp/pf4j/pf4j/src/test/resources
[INFO] 
[INFO] --- maven-compiler-plugin:2.3.2:testCompile (default-testCompile) @ pf4j ---
[INFO] Compiling 11 source files to /home/ocau/tmp/pf4j/pf4j/target/test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.17:test (default-test) @ pf4j ---
[INFO] Surefire report directory: /home/ocau/tmp/pf4j/pf4j/target/surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running ro.fortsoft.pf4j.DefaultExtensionFactoryTest
SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.043 sec - in ro.fortsoft.pf4j.DefaultExtensionFactoryTest
Running ro.fortsoft.pf4j.DefaultPluginStatusProviderTest
Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.039 sec - in ro.fortsoft.pf4j.DefaultPluginStatusProviderTest
Running ro.fortsoft.pf4j.DefaultPluginFactoryTest
Tests run: 4, Failures: 0, Errors: 4, Skipped: 0, Time elapsed: 0.039 sec <<< FAILURE! - in ro.fortsoft.pf4j.DefaultPluginFactoryTest
testCreateFailNotFound(ro.fortsoft.pf4j.DefaultPluginFactoryTest)  Time elapsed: 0.035 sec  <<< ERROR!
java.lang.ExceptionInInitializerError: null
	at org.mockito.internal.configuration.plugins.Plugins.getStackTraceCleanerProvider(Plugins.java:17)
	at org.mockito.internal.exceptions.stacktrace.StackTraceFilter.<clinit>(StackTraceFilter.java:21)
	at org.mockito.internal.exceptions.stacktrace.ConditionalStackTraceFilter.<init>(ConditionalStackTraceFilter.java:17)
	at org.mockito.exceptions.base.MockitoException.filterStackTrace(MockitoException.java:41)
	at org.mockito.exceptions.base.MockitoException.<init>(MockitoException.java:30)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:35)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:12)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:11)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:23)
	at org.mockito.internal.MockitoCore.<init>(MockitoCore.java:44)
	at org.mockito.Mockito.<clinit>(Mockito.java:1101)
	at ro.fortsoft.pf4j.DefaultPluginFactoryTest.testCreateFailNotFound(DefaultPluginFactoryTest.java:78)

testCreateFail(ro.fortsoft.pf4j.DefaultPluginFactoryTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.mockito.Mockito
	at ro.fortsoft.pf4j.DefaultPluginFactoryTest.testCreateFail(DefaultPluginFactoryTest.java:60)

testCreate(ro.fortsoft.pf4j.DefaultPluginFactoryTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.mockito.Mockito
	at ro.fortsoft.pf4j.DefaultPluginFactoryTest.testCreate(DefaultPluginFactoryTest.java:41)

testCreateFailConstructor(ro.fortsoft.pf4j.DefaultPluginFactoryTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NoClassDefFoundError: Could not initialize class org.mockito.Mockito
	at ro.fortsoft.pf4j.DefaultPluginFactoryTest.testCreateFailConstructor(DefaultPluginFactoryTest.java:96)

Running ro.fortsoft.pf4j.ManifestPluginDescriptorFinderTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.031 sec - in ro.fortsoft.pf4j.ManifestPluginDescriptorFinderTest
Running ro.fortsoft.pf4j.DefaultPluginRepositoryTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.001 sec - in ro.fortsoft.pf4j.DefaultPluginRepositoryTest
Running ro.fortsoft.pf4j.PluginDependencyTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec - in ro.fortsoft.pf4j.PluginDependencyTest

Results :

Tests in error: 
  DefaultPluginFactoryTest.testCreateFailNotFound:78 » ExceptionInInitializer
  DefaultPluginFactoryTest.testCreateFail:60 NoClassDefFound Could not initializ...
  DefaultPluginFactoryTest.testCreate:41 NoClassDefFound Could not initialize cl...
  DefaultPluginFactoryTest.testCreateFailConstructor:96 NoClassDefFound Could no...

Tests run: 21, Failures: 0, Errors: 4, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] PF4J Parent ........................................ SUCCESS [  0.715 s]
[INFO] PF4J ............................................... FAILURE [ 11.873 s]
[INFO] Demo Parent ........................................ SKIPPED
[INFO] Demo Api ........................................... SKIPPED
[INFO] Demo App ........................................... SKIPPED
[INFO] Demo Plugins Parent ................................ SKIPPED
[INFO] Demo Plugin #1 ..................................... SKIPPED
[INFO] Demo Plugin #2 ..................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.746 s
[INFO] Finished at: 2017-01-24T11:29:19+01:00
[INFO] Final Memory: 18M/61M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.17:test (default-test) on project pf4j: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/ocau/tmp/pf4j/pf4j/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :pf4j
```

I don't know what to do now,
If you have any clue...

**Comment by decebals** [comment]
I cannot reproduce your error. I use Ubuntu 16.04
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] PF4J Parent ........................................ SUCCESS [  1.490 s]
[INFO] PF4J ............................................... SUCCESS [  6.978 s]
[INFO] Demo Parent ........................................ SUCCESS [  0.011 s]
[INFO] Demo Api ........................................... SUCCESS [  0.498 s]
[INFO] Demo App ........................................... SUCCESS [  1.610 s]
[INFO] Demo Plugins Parent ................................ SUCCESS [  0.470 s]
[INFO] Demo Plugin #1 ..................................... SUCCESS [  0.800 s]
[INFO] Demo Plugin #2 ..................................... SUCCESS [  0.526 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 12.610 s
[INFO] Finished at: 2017-01-24T17:28:29+02:00
[INFO] Final Memory: 54M/344M
```

```
$ java -version
java version "1.7.0_79"
Java(TM) SE Runtime Environment (build 1.7.0_79-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.79-b02, mixed mode)
```

What Java version you use to compile PF4J?

To skip tests you can run with `-DskipTests` (for example `mvn -DskipTests clean package`).

**Comment by bigk-fr** [comment]
I was using openjdk 9
I tried the same commands under oracle jdk 1.8 and it worked well.
Thank you.

**Comment by bigk-fr** [comment]
Just for info, I also have tried earlier with `-DskipTests` under openjdk 9 and it failed
