### ISSUE TITLE
Can't manage to use slf4j together with plugins

### ISSUE THREAD

**Issue by lyze237** [decebals/pf4j#148]
Hello!

I'm currently trying to use slf4j (over either simple or log4j) and I always get warnings that it found multiple slf4j bindings:

The following warning message appears once per plugin, which is a gigantic chunk when I have a couple of them loaded!

```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/Users/lyze/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-log4j12/1.7.5/6edffc576ce104ec769d954618764f39f0f0f10d/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/D:/Workspace/java/darkowlbot/Core/plugins/DarkOwlBot-TelegramClient-0.0.26/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by 
log4j:ERROR [ro.fortsoft.pf4j.PluginClassLoader@6bc168e5] whereas object of type 
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [sun.misc.Launcher$AppClassLoader@73d16e93].
log4j:ERROR Could not instantiate appender named "Console".
log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by 
log4j:ERROR [ro.fortsoft.pf4j.PluginClassLoader@6bc168e5] whereas object of type 
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [sun.misc.Launcher$AppClassLoader@73d16e93].
log4j:ERROR Could not instantiate appender named "Console".
log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by 
log4j:ERROR [ro.fortsoft.pf4j.PluginClassLoader@6bc168e5] whereas object of type 
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [sun.misc.Launcher$AppClassLoader@73d16e93].
log4j:ERROR Could not instantiate appender named "Console".
log4j:ERROR A "org.apache.log4j.ConsoleAppender" object is not assignable to a "org.apache.log4j.Appender" variable.
log4j:ERROR The class "org.apache.log4j.Appender" was loaded by 
log4j:ERROR [ro.fortsoft.pf4j.PluginClassLoader@6bc168e5] whereas object of type 
log4j:ERROR "org.apache.log4j.ConsoleAppender" was loaded by [sun.misc.Launcher$AppClassLoader@73d16e93].
log4j:ERROR Could not instantiate appender named "Console".
log4j:WARN No appenders could be found for logger (com.thyllian.DarkOwlBot.plugins.clients.telegram.TelegramPlugin).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```

Log4j properties inside startup project:

```
log4j.rootLogger=DEBUG, Console

#
# PF4J log
#
log4j.logger.ro.fortsoft.pf4j=INFO, Console
log4j.logger.ro.fortsoft.pf4j.PluginClassLoader=WARN, Console
log4j.additivity.ro.fortsoft.pf4j=false
log4j.logger.com.thyllian=TRACE, Console

#
# Appenders
#
log4j.appender.Console=org.apache.log4j.ConsoleAppender
log4j.appender.Console.layout=org.apache.log4j.PatternLayout
#log4j.appender.Console.layout.conversionPattern=%-5p - %-32.32c{1} - %m\n
log4j.appender.Console.layout.ConversionPattern=%d %p %c - %m%n
```

Everything works however properly, messages get printed just fine, though multiple times.

Setup is just:

main build.gradle:
```
subprojects {
    dependencies {
         compile 'ro.fortsoft.pf4j:pf4j:1.3.0'
         compile group: 'org.slf4j', name: 'slf4j-log4j12', version: '1.7.5'
    }
}
```

**Comment by lyze237** [comment]
When I try to move the slf4j-log4j12 library to the main startup project instead of every project it doesn't compile with the following error:

```
Exception in thread "main" java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of ro/fortsoft/pf4j/PluginClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:299)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at com.thyllian.DarkOwlBot.plugins.clients.discord.DiscordPlugin.<clinit>(DiscordPlugin.java:16)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ro.fortsoft.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:64)
	at ro.fortsoft.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:78)
	at ro.fortsoft.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:315)
	at com.thyllian.darkowlbot.Startup.startup(Startup.java:79)
	at com.thyllian.darkowlbot.Startup.main(Startup.java:23)
:Core:run FAILED
```

**Comment by decebals** [comment]
@lyze237 PF4J comes with a dependency to slf4j 1.7.5 (https://github.com/decebals/pf4j/blob/master/pf4j/pom.xml#L31). 
You can add a concrete slf4j implementation like in demo project (https://github.com/decebals/pf4j/blob/master/demo/app/pom.xml#L89) where slf4j-log4j12 with log4j 1.2.16.
My feeling is that one or more of yours plugins come with a (transitive) dependency to slf4j (possible other version). In this case solution please try to exclude any dependency to slf4j from yours plugins.

**Comment by lyze237** [comment]
I've tried that but sadly that doesn't work for me?

Stripped down everything to have only a bare minimum I can use and tried to do the thing you did with maven:

All external libraries: http://i.imgur.com/Xcn6jvo.png

Project gradle file:

```
subprojects {
    apply plugin: 'java'

    repositories {
        mavenLocal()
        mavenCentral()
        jcenter()
    }

    dependencies {
        compile 'ro.fortsoft.pf4j:pf4j:1.3.0'
        compile 'commons-io:commons-io:2.5'
        compile 'org.projectlombok:lombok:1.16.16'
        compile group: 'com.fasterxml.jackson.core', name: 'jackson-databind', version: '2.9.0.pr3'
        testCompile group: 'junit', name: 'junit', version: '4.+'
    }
}
```

App subproject gradle file:

```
dependencies {
    compile project(':PluginApi')
    compile "org.apache.logging.log4j:log4j:2.5"
    compile group: 'org.slf4j', name: 'slf4j-log4j12', version: '1.7.5'
}
```

Plugin Api gradle file:

```
dependencies {
    compile "org.apache.logging.log4j:log4j:2.5"
    compile group: 'org.slf4j', name: 'slf4j-log4j12', version: '1.7.5'
}
```

Plugin gradle file:
```
dependencies {
    compileOnly project(':PluginApi')
}
```

And it gives me the following error: once it loads the first plugin:
```
Exception in thread "main" java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of ro/fortsoft/pf4j/PluginClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:299)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at com.thyllian.DarkOwlBot.plugins.TestPlugin.<clinit>(TestPlugin.java:14)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ro.fortsoft.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:64)
	at ro.fortsoft.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:78)
	at ro.fortsoft.pf4j.AbstractPluginManager.startPlugins(AbstractPluginManager.java:315)
	at com.thyllian.darkowlbot.Startup.startup(Startup.java:101)
	at com.thyllian.darkowlbot.Startup.main(Startup.java:27)
```

I'll try it with the sample gradle project and will report back in ~1h.

**Comment by lyze237** [comment]
Yeah when I checkout the current gradle project and replace all System.out.println's with:

```
private static Logger logger = LoggerFactory.getLogger(<ClassName>.class);
[...]
log.info(<thing>);
```

I get the error:

```
147 [main] INFO ro.fortsoft.pf4j.DefaultPluginManager - Start plugin 'WelcomePlugin:1.0.0'
Exception in thread "main" java.lang.LinkageError: loader constraint violation: when resolving method "org.slf4j.impl.StaticLoggerBinder.getLoggerFactory()Lorg/slf4j/ILoggerFactory;" the class loader (instance of ro/fortsoft/pf4j/PluginClassLoader) of the current class, org/slf4j/LoggerFactory, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/slf4j/impl/StaticLoggerBinder, have different Class objects for the type org/slf4j/ILoggerFactory used in the signature
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:299)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:269)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:281)
	at ro.fortsoft.pf4j.demo.welcome.WelcomePlugin.<clinit>(WelcomePlugin.java:31)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at ro.fortsoft.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:64)
	at ro.fortsoft.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:75)
	at ro.fortsoft.pf4j.DefaultPluginManager.startPlugins(DefaultPluginManager.java:231)
	at ro.fortsoft.pf4j.demo.Boot.main(Boot.java:51)
```

**Comment by lyze237** [comment]
See #149 for a fix
