### ISSUE TITLE
FileSystemException when I call deletePlugin after getExtensions

### ISSUE THREAD

**Issue by decebals** [decebals/pf4j#156]
I try to use pf4j for dynamic loading plugins from jar files to my app and sometimes I need to update my jars, currently I have problem, `getExtensions(Class<T> type)` method blocks my jar file and I can't delete it by calling `deletePlugin(String pluginId)`, I receive exception:
```
[main] INFO ro.fortsoft.pf4j.AbstractPluginManager - Stop plugin 'rule-plugin:0.0.1'
Exception in thread "main" java.lang.RuntimeException: java.nio.file.FileSystemException: d:\plugins\test-rules-1.0-SNAPSHOT.jar: The process cannot access the file because it is being used by another process.
        at ro.fortsoft.pf4j.BasePluginRepository.deletePluginPath(BasePluginRepository.java:75)
        at ro.fortsoft.pf4j.AbstractPluginManager.deletePlugin(AbstractPluginManager.java:301)
        at com.datawatch.PluginsApp.main(PluginsApp.java:47)
Caused by: java.nio.file.FileSystemException: d:\plugins\test-rules-1.0-SNAPSHOT.jar: The process cannot access the file because it is being used by another process.
```

For more information see https://groups.google.com/forum/#!topic/pf4j/NYVJ6KHqr-I.

**Comment by decebals** [comment]
I think that the problem appears because I read a file (input stream, reader) and I forget to close it.

**Comment by janhoy** [comment]
Closing. Please re-open or file a new issue if there are still problems :)
