### ISSUE TITLE
Wrong side of dependencies checked during unload of a plugin

### ISSUE THREAD

**Issue by greatman** [decebals/pf4j#161]
Reference: https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/ro/fortsoft/pf4j/AbstractPluginManager.java#L254

Currently, when unloading a plugin, it unloads the plugins it is being dependent on instead of plugins being dependent on it

stopPlugin() got the proper check : https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/ro/fortsoft/pf4j/AbstractPluginManager.java#L431

To put in a example:
Plugin A/B/C depends on D.
I unload Plugin A, it triggers a unload on plugin D which cause a stop on B&C.

The expected behavior is:
Plugin A/B/C depends on D.
I unload Plugin A, only A unloads.

I am using the MANIFEST.MF property Plugin-Dependencies.

**Comment by decebals** [comment]
Thanks for reporting!
Can you submit a PR with the fix?

**Comment by decebals** [comment]
I updated the SNAPSHOT version to reflect this fix. Please test it and let me know if everything is OK.

P.S
I am in the process of revisit the dependents/dependencies checking for each operation that modify the plugins states (stop, load, unload, ...).

**Comment by greatman** [comment]
When trying to load my plugin, it does that after being unloaded:
`[JDA MainWS-ReadThread] INFO com.greatmancode.legendarybot.MessageListener - [test]greatman: !unload ilvlCommand
[JDA MainWS-ReadThread] INFO ro.fortsoft.pf4j.AbstractPluginManager - Stop plugin 'ilvlCommand@0.0.1'
[JDA MainWS-ReadThread] INFO com.greatmancode.legendarybot.commands.ilvl.IlvlCommand - command !ilvl unloaded
[JDA MainWS-ReadThread] INFO ro.fortsoft.pf4j.AbstractPluginManager - Unload plugin 'ilvlCommand@0.0.1'
[JDA MainWS-ReadThread] INFO com.greatmancode.legendarybot.MessageListener - [test]greatman: !load
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\affixcommand-2.0-SNAPSHOT-bin' already loaded with id 'affixPlugin'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\blizzardcscommand-2.0-SNAPSHOT-bin' already loaded with id 'blizzardcsCommand'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\botgeneral-2.0-SNAPSHOT-bin' already loaded with id 'botGeneralPlugin'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\botplay-2.0-SNAPSHOT-bin' already loaded with id 'botPlay'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\botstats-2.0-SNAPSHOT-bin' already loaded with id 'statsPlugin'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\customcommands-2.0-SNAPSHOT-bin' already loaded with id 'customCommand'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\gifcommand-2.0-SNAPSHOT-bin' already loaded with id 'gifCommand'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\invasioncommand-2.0-SNAPSHOT-bin' already loaded with id 'invasionCommand'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\legendarycheck-2.0-SNAPSHOT-bin' already loaded with id 'legendaryCheckPlugin'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\legionbuilding-2.0-SNAPSHOT-bin' already loaded with id 'legionBuildingCommand'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\logcommand-2.0-SNAPSHOT-bin' already loaded with id 'logCommand'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\lookupCommands-2.0-SNAPSHOT-bin' already loaded with id 'lookupCommands'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\music-2.0-SNAPSHOT-bin' already loaded with id 'musicPlugin'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\mythicplusrank-2.0-SNAPSHOT-bin' already loaded with id 'mythicPlusCommand'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\owrankcommand-2.0-SNAPSHOT-bin' already loaded with id 'owrankCommand'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\raidrank-2.0-SNAPSHOT-bin' already loaded with id 'raidRankCommand'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\servercommand-2.0-SNAPSHOT-bin' already loaded with id 'serverCommand'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\streamers-2.0-SNAPSHOT-bin' already loaded with id 'streamersPlugin'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\tokencommand-2.0-SNAPSHOT-bin' already loaded with id 'tokenCommand'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\wowlink-2.0-SNAPSHOT-bin' already loaded with id 'wowLink'
[JDA MainWS-ReadThread] WARN ro.fortsoft.pf4j.AbstractPluginManager - Plugin 'plugins\wprank-2.0-SNAPSHOT-bin' already loaded with id 'wprankCommand'
[JDA MainWS-ReadThread] ERROR ro.fortsoft.pf4j.AbstractPluginManager - Dependencies '[wowLink]' not found
ro.fortsoft.pf4j.DependencyResolver$DependenciesNotFoundException: Dependencies '[wowLink]' not found
        at ro.fortsoft.pf4j.AbstractPluginManager.resolvePlugins(AbstractPluginManager.java:748)
        at ro.fortsoft.pf4j.AbstractPluginManager.loadPlugins(AbstractPluginManager.java:238)
        at com.greatmancode.legendarybot.commands.LoadCommand.execute(LoadCommand.java:52)
        at com.greatmancode.legendarybot.api.commands.CommandHandler.handle(CommandHandler.java:102)
        at com.greatmancode.legendarybot.MessageListener.onMessageReceived(MessageListener.java:66)
        at net.dv8tion.jda.core.hooks.ListenerAdapter.onEvent(ListenerAdapter.java:385)
        at net.dv8tion.jda.core.hooks.InterfacedEventManager.handle(InterfacedEventManager.java:84)
        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleDefaultMessage(MessageCreateHandler.java:128)
        at net.dv8tion.jda.core.handle.MessageCreateHandler.handleInternally(MessageCreateHandler.java:49)
        at net.dv8tion.jda.core.handle.SocketHandler.handle(SocketHandler.java:37)
        at net.dv8tion.jda.core.requests.WebSocketClient.handleEvent(WebSocketClient.java:768)
        at net.dv8tion.jda.core.requests.WebSocketClient.onTextMessage(WebSocketClient.java:498)
        at com.neovisionaries.ws.client.ListenerManager.callOnTextMessage(ListenerManager.java:352)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:260)
        at com.neovisionaries.ws.client.ReadingThread.callOnTextMessage(ReadingThread.java:238)
        at com.neovisionaries.ws.client.ReadingThread.handleTextFrame(ReadingThread.java:963)
        at com.neovisionaries.ws.client.ReadingThread.handleFrame(ReadingThread.java:746)
        at com.neovisionaries.ws.client.ReadingThread.main(ReadingThread.java:108)
        at com.neovisionaries.ws.client.ReadingThread.runMain(ReadingThread.java:64)
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)`

**Comment by greatman** [comment]
Fixed in the referenced PR.
