### ISSUE TITLE
DefaultExtensionFactory java.lang.InstantiationException 

### ISSUE THREAD

**Issue by Magnusgaertner** [decebals/pf4j#183]
```java
package de.opendiabetes.vault;


import org.pf4j.DefaultPluginManager;
import org.pf4j.PluginManager;

import java.nio.file.Paths;

public class Main {

    public static void main(String... args){
            PluginManager manager = new DefaultPluginManager(Paths.get("export"));
            manager.loadPlugins();
            manager.startPlugins();

            System.out.println( manager.getExtensionClassNames("Plugin1"));
            System.out.println(manager.getExtensionFactory().create(PluginInterface.class));
            PluginInterface plugin1 = manager.getExtensions(PluginInterface.class).get(0);

            plugin1.simpleTestCall();
    }
}

```

```java
package de.opendiabetes.vault;

import org.pf4j.ExtensionPoint;
import org.pf4j.Plugin;

public interface PluginInterface extends ExtensionPoint{
    public String simpleTestCall();
}
```

```java
package de.opendiabetes.vault;

import org.pf4j.Plugin;
import org.pf4j.PluginWrapper;

public class Plugin1 extends Plugin{
    public Plugin1(PluginWrapper wrapper) {
        super(wrapper);
    }
    public static class Plugin1Implementation implements PluginInterface{
        public Plugin1Implementation(){}

        public String simpleTestCall() {
            System.out.println("this is plugin1!");
            return "this is plugin1!";
        }
    }

}
```

**running this somehow works but I cannot figure out, why the java.lang.InstantiationException gets thrown.** 

```
/usr/lib/jvm/java-8-oracle/bin/java -javaagent:/home/magnus/idea-IC-172.4343.14/lib/idea_rt.jar=46035:/home/magnus/idea-IC-172.4343.14/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-oracle/jre/lib/javaws.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-oracle/jre/lib/plugin.jar:/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/home/magnus/BPTest/out/production/Test:/home/magnus/BPTest/lib/log4j-1.2.16.jar:/home/magnus/BPTest/lib/pf4j-2.0.0.jar:/home/magnus/BPTest/lib/slf4j-api-1.7.5.jar:/home/magnus/BPTest/lib/slf4j-log4j12-1.7.5.jar de.opendiabetes.vault.Main
2017-12-14 12:35:36,135 INFO org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
2017-12-14 12:35:36,135 INFO org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
2017-12-14 12:35:36,139 INFO org.pf4j.DefaultPluginManager - PF4J version 2.0.0 in 'deployment' mode
2017-12-14 12:35:36,139 DEBUG org.pf4j.AbstractPluginManager - Lookup plugins in 'export'
2017-12-14 12:35:36,142 DEBUG org.pf4j.AbstractPluginManager - Found 1 possible plugins: [export/Plugin1]
2017-12-14 12:35:36,142 DEBUG org.pf4j.AbstractPluginManager - Use 'org.pf4j.CompoundPluginDescriptorFinder@45ff54e6' to find plugins descriptors
2017-12-14 12:35:36,142 DEBUG org.pf4j.AbstractPluginManager - Finding plugin descriptor for plugin 'export/Plugin1'
2017-12-14 12:35:36,142 DEBUG org.pf4j.CompoundPluginDescriptorFinder - 'org.pf4j.PropertiesPluginDescriptorFinder@2328c243' is applicable for plugin 'export/Plugin1'
2017-12-14 12:35:36,143 DEBUG org.pf4j.PropertiesPluginDescriptorFinder - Lookup plugin descriptor in 'export/Plugin1/plugin.properties'
2017-12-14 12:35:36,147 DEBUG org.pf4j.AbstractPluginManager - Found descriptor PluginDescriptor [pluginId=Plugin1, pluginClass=de.opendiabetes.vault.Plugin1, version=0.0.1, provider=Magnus, dependencies=[], description=, requires=*, license=null]
2017-12-14 12:35:36,147 DEBUG org.pf4j.AbstractPluginManager - Class 'de.opendiabetes.vault.Plugin1' for plugin 'export/Plugin1'
2017-12-14 12:35:36,147 DEBUG org.pf4j.AbstractPluginManager - Loading plugin 'export/Plugin1'
2017-12-14 12:35:36,147 DEBUG org.pf4j.CompoundPluginLoader - 'org.pf4j.DefaultPluginLoader@7591083d' is applicable for plugin 'export/Plugin1'
2017-12-14 12:35:36,148 DEBUG org.pf4j.PluginClassLoader - Add 'file:/home/magnus/BPTest/export/Plugin1/classes/'
2017-12-14 12:35:36,148 DEBUG org.pf4j.AbstractPluginManager - Loaded plugin 'export/Plugin1' with class loader 'org.pf4j.PluginClassLoader@736e9adb'
2017-12-14 12:35:36,148 DEBUG org.pf4j.AbstractPluginManager - Creating wrapper for plugin 'export/Plugin1'
2017-12-14 12:35:36,150 DEBUG org.pf4j.AbstractPluginManager - Created wrapper 'PluginWrapper [descriptor=PluginDescriptor [pluginId=Plugin1, pluginClass=de.opendiabetes.vault.Plugin1, version=0.0.1, provider=Magnus, dependencies=[], description=, requires=*, license=null], pluginPath=export/Plugin1]' for plugin 'export/Plugin1'
2017-12-14 12:35:36,151 DEBUG org.pf4j.DependencyResolver - Graph: 
   Plugin1 -> []
2017-12-14 12:35:36,151 DEBUG org.pf4j.DependencyResolver - Plugins order: [Plugin1]
2017-12-14 12:35:36,151 INFO org.pf4j.AbstractPluginManager - Plugin 'Plugin1@0.0.1' resolved
2017-12-14 12:35:36,152 INFO org.pf4j.AbstractPluginManager - Start plugin 'Plugin1@0.0.1'
2017-12-14 12:35:36,152 DEBUG org.pf4j.DefaultExtensionFactory - Create instance for plugin 'de.opendiabetes.vault.Plugin1'
2017-12-14 12:35:36,152 TRACE org.pf4j.PluginClassLoader - Received request to load class 'de.opendiabetes.vault.Plugin1'
2017-12-14 12:35:36,152 TRACE org.pf4j.PluginClassLoader - Received request to load class 'org.pf4j.Plugin'
2017-12-14 12:35:36,152 TRACE org.pf4j.PluginClassLoader - Delegate the loading of class 'org.pf4j.Plugin' to parent
2017-12-14 12:35:36,153 TRACE org.pf4j.PluginClassLoader - Found class 'de.opendiabetes.vault.Plugin1' in plugin classpath
2017-12-14 12:35:36,153 TRACE org.pf4j.PluginClassLoader - Received request to load class 'org.pf4j.PluginWrapper'
2017-12-14 12:35:36,153 TRACE org.pf4j.PluginClassLoader - Delegate the loading of class 'org.pf4j.PluginWrapper' to parent
2017-12-14 12:35:36,153 DEBUG org.pf4j.AbstractPluginManager - Fire 'PluginStateEvent [plugin=Plugin1, newState=STARTED, oldState=CREATED]' to 'org.pf4j.DefaultExtensionFinder@619a5dff'
2017-12-14 12:35:36,153 DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storages from classpath
2017-12-14 12:35:36,154 DEBUG org.pf4j.AbstractExtensionFinder - No extensions found
2017-12-14 12:35:36,154 DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storages from plugins
2017-12-14 12:35:36,154 DEBUG org.pf4j.LegacyExtensionFinder - Reading extensions storage from plugin 'Plugin1'
2017-12-14 12:35:36,154 DEBUG org.pf4j.LegacyExtensionFinder - Read '/home/magnus/BPTest/export/Plugin1/classes/META-INF/extensions.idx'
2017-12-14 12:35:36,156 DEBUG org.pf4j.AbstractExtensionFinder - Found possible 1 extensions:
2017-12-14 12:35:36,156 DEBUG org.pf4j.AbstractExtensionFinder -    de.opendiabetes.vault.Plugin1$Plugin1Implementation
[de.opendiabetes.vault.Plugin1$Plugin1Implementation]
2017-12-14 12:35:36,156 DEBUG org.pf4j.DefaultExtensionFactory - Create instance for extension 'de.opendiabetes.vault.PluginInterface'
2017-12-14 12:35:36,157 ERROR org.pf4j.DefaultExtensionFactory - de.opendiabetes.vault.PluginInterface
java.lang.InstantiationException: de.opendiabetes.vault.PluginInterface
	at java.lang.Class.newInstance(Class.java:427)
	at org.pf4j.DefaultExtensionFactory.create(DefaultExtensionFactory.java:40)
	at de.opendiabetes.vault.Main.main(Main.java:17)
Caused by: java.lang.NoSuchMethodException: de.opendiabetes.vault.PluginInterface.<init>()
	at java.lang.Class.getConstructor0(Class.java:3082)
	at java.lang.Class.newInstance(Class.java:412)
	... 2 more
null
2017-12-14 12:35:36,159 DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'de.opendiabetes.vault.PluginInterface'
2017-12-14 12:35:36,159 DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'de.opendiabetes.vault.PluginInterface' for plugin 'null'
2017-12-14 12:35:36,159 DEBUG org.pf4j.AbstractExtensionFinder - Finding extensions of extension point 'de.opendiabetes.vault.PluginInterface' for plugin 'Plugin1'
2017-12-14 12:35:36,159 TRACE org.pf4j.AbstractExtensionFinder - Checking extensions from plugin 'Plugin1'
2017-12-14 12:35:36,159 DEBUG org.pf4j.AbstractExtensionFinder - Loading class 'de.opendiabetes.vault.Plugin1$Plugin1Implementation' using class loader 'org.pf4j.PluginClassLoader@736e9adb'
2017-12-14 12:35:36,159 TRACE org.pf4j.PluginClassLoader - Received request to load class 'de.opendiabetes.vault.Plugin1$Plugin1Implementation'
2017-12-14 12:35:36,160 TRACE org.pf4j.PluginClassLoader - Received request to load class 'de.opendiabetes.vault.PluginInterface'
2017-12-14 12:35:36,160 TRACE org.pf4j.PluginClassLoader - Search in dependencies for class 'de.opendiabetes.vault.PluginInterface'
2017-12-14 12:35:36,160 TRACE org.pf4j.PluginClassLoader - Couldn't find class 'de.opendiabetes.vault.PluginInterface' in plugin classpath. Delegating to parent
2017-12-14 12:35:36,160 TRACE org.pf4j.PluginClassLoader - Received request to load class 'java.lang.Object'
2017-12-14 12:35:36,160 TRACE org.pf4j.PluginClassLoader - Search in dependencies for class 'java.lang.Object'
2017-12-14 12:35:36,160 TRACE org.pf4j.PluginClassLoader - Couldn't find class 'java.lang.Object' in plugin classpath. Delegating to parent
2017-12-14 12:35:36,160 TRACE org.pf4j.PluginClassLoader - Found class 'de.opendiabetes.vault.Plugin1$Plugin1Implementation' in plugin classpath
2017-12-14 12:35:36,160 DEBUG org.pf4j.AbstractExtensionFinder - Checking extension type 'de.opendiabetes.vault.Plugin1$Plugin1Implementation'
2017-12-14 12:35:36,162 DEBUG org.pf4j.AbstractExtensionFinder - Added extension 'de.opendiabetes.vault.Plugin1$Plugin1Implementation' with ordinal 0
2017-12-14 12:35:36,162 DEBUG org.pf4j.AbstractExtensionFinder - Found 1 extensions for extension point 'de.opendiabetes.vault.PluginInterface'
2017-12-14 12:35:36,162 DEBUG org.pf4j.AbstractExtensionFinder - Found 1 extensions for extension point 'de.opendiabetes.vault.PluginInterface'
2017-12-14 12:35:36,162 DEBUG org.pf4j.DefaultExtensionFactory - Create instance for extension 'de.opendiabetes.vault.Plugin1$Plugin1Implementation'
2017-12-14 12:35:36,162 TRACE org.pf4j.PluginClassLoader - Received request to load class 'java.lang.System'
2017-12-14 12:35:36,162 TRACE org.pf4j.PluginClassLoader - Search in dependencies for class 'java.lang.System'
2017-12-14 12:35:36,162 TRACE org.pf4j.PluginClassLoader - Couldn't find class 'java.lang.System' in plugin classpath. Delegating to parent
2017-12-14 12:35:36,163 TRACE org.pf4j.PluginClassLoader - Received request to load class 'java.io.PrintStream'
2017-12-14 12:35:36,163 TRACE org.pf4j.PluginClassLoader - Search in dependencies for class 'java.io.PrintStream'
2017-12-14 12:35:36,163 TRACE org.pf4j.PluginClassLoader - Couldn't find class 'java.io.PrintStream' in plugin classpath. Delegating to parent
this is plugin1!

Process finished with exit code 0

```

**Comment by decebals** [comment]
First of all please remove lines with `System.out`
```java
PluginManager manager = new DefaultPluginManager(Paths.get("export"));
manager.loadPlugins();
manager.startPlugins();

PluginInterface plugin1 = manager.getExtensions(PluginInterface.class).get(0);
plugin1.simpleTestCall();
```

Line
```
System.out.println(manager.getExtensionFactory().create(PluginInterface.class));
```
it's not OK because you try to instantiate an interface (your error says this thing). `ExtensionFactory` from plugin manager is used internally by framework.

Other observation is that you forget to mark `Plugin1Implementation` as extension (via @Extension)
```java
@Extension
public static class Plugin1Implementation implements PluginInterface {
    ...
}
```

I don't know how above class is found as extension without @Extension annotation marker. To edit manually  `META-INF/extensions.idx` it's wrong (this file is created my PF4J automatically).

**Comment by decebals** [comment]
@Magnusgaertner Any news about this issue? I wish to close it if my previous comment helped you to solve it.

**Comment by decebals** [comment]
I will close it because I didn't receive a response to my previous comment. Please reopen the issue if the problem persist.
