### ISSUE TITLE
Using .jar Plugins

### ISSUE THREAD

**Issue by lucasbuschlinger** [decebals/pf4j#196]
Hey decebals and community,

I'm currently trying to get .jar plugins working.

The jar currently looks like this (two folders from jar root):
```
classes/
    de/opendiabetes/path/to/classes
    META-INF/extensions.idx
```
and
```
META-INF/MANIFEST.MF
```

The jar and manifest are generated by the ant jar task.

The manifest looks like this:
```
Manifest-Version: 1.0
Ant-Version: Apache Ant 1.9.4
Created-By: 1.8.0_151-b12 (Oracle Corporation)
Plugin-Class: de.opendiabetes.vault.plugin.importer.googlefit.GoogleFi
 tCSVImporter
Plugin-Dependencies: 
Plugin-Id: GoogleFitCSVImporter
Plugin-Provider: OpenDiabetes
Plugin-Version: 0.0.1
```

The jar is found and resolved correctly but when it should be loaded the following happens:
```
2018-01-21 16:38:38,620 INFO org.pf4j.DefaultPluginStatusProvider - Enabled plugins: []
2018-01-21 16:38:38,622 INFO org.pf4j.DefaultPluginStatusProvider - Disabled plugins: []
2018-01-21 16:38:38,624 INFO org.pf4j.DefaultPluginManager - PF4J version 2.1.0 in 'deployment' mode
2018-01-21 16:38:38,624 DEBUG org.pf4j.AbstractPluginManager - Lookup plugins in 'export'
2018-01-21 16:38:38,630 DEBUG org.pf4j.AbstractPluginManager - Found 1 possible plugins: [export\GoogleFitCSVImporter-0.0.1.jar]
2018-01-21 16:38:38,630 DEBUG org.pf4j.AbstractPluginManager - Use 'org.pf4j.CompoundPluginDescriptorFinder@75c072cb' to find plugins descriptors
2018-01-21 16:38:38,630 DEBUG org.pf4j.AbstractPluginManager - Finding plugin descriptor for plugin 'export\GoogleFitCSVImporter-0.0.1.jar'
2018-01-21 16:38:38,631 DEBUG org.pf4j.CompoundPluginDescriptorFinder - 'org.pf4j.PropertiesPluginDescriptorFinder@1f1c7bf6' is applicable for plugin 'export\GoogleFitCSVImporter-0.0.1.jar'
2018-01-21 16:38:38,642 ERROR org.pf4j.CompoundPluginDescriptorFinder - C:\export\GoogleFitCSVImporter-0.0.1.jar
2018-01-21 16:38:38,643 DEBUG org.pf4j.CompoundPluginDescriptorFinder - 'org.pf4j.ManifestPluginDescriptorFinder@53ca01a2' is applicable for plugin 'export\GoogleFitCSVImporter-0.0.1.jar'
2018-01-21 16:38:38,644 DEBUG org.pf4j.AbstractPluginManager - Found descriptor PluginDescriptor [pluginId=GoogleFitCSVImporter, pluginClass=de.opendiabetes.vault.plugin.importer.googlefit.GoogleFitCSVImporter, version=0.0.1, provider=OpenDiabetes, dependencies=[], description=, requires=*, license=null]
2018-01-21 16:38:38,644 DEBUG org.pf4j.AbstractPluginManager - Class 'de.opendiabetes.vault.plugin.importer.googlefit.GoogleFitCSVImporter' for plugin 'export\GoogleFitCSVImporter-0.0.1.jar'
2018-01-21 16:38:38,644 DEBUG org.pf4j.AbstractPluginManager - Loading plugin 'export\GoogleFitCSVImporter-0.0.1.jar'
2018-01-21 16:38:38,644 DEBUG org.pf4j.CompoundPluginLoader - 'org.pf4j.DefaultPluginLoader@1a84f40f' is not applicable for plugin 'export\GoogleFitCSVImporter-0.0.1.jar'
2018-01-21 16:38:38,644 DEBUG org.pf4j.CompoundPluginLoader - 'org.pf4j.JarPluginLoader@23282c25' is applicable for plugin 'export\GoogleFitCSVImporter-0.0.1.jar'
2018-01-21 16:38:38,646 DEBUG org.pf4j.PluginClassLoader - Add 'file:/C:/Users/Lucas%20Buschlinger/Desktop/Studium/BP/Code/export/GoogleFitCSVImporter-0.0.1.jar'
2018-01-21 16:38:38,646 DEBUG org.pf4j.AbstractPluginManager - Loaded plugin 'export\GoogleFitCSVImporter-0.0.1.jar' with class loader 'org.pf4j.PluginClassLoader@3b2da18f'
2018-01-21 16:38:38,646 DEBUG org.pf4j.AbstractPluginManager - Creating wrapper for plugin 'export\GoogleFitCSVImporter-0.0.1.jar'
2018-01-21 16:38:38,648 DEBUG org.pf4j.AbstractPluginManager - Created wrapper 'PluginWrapper [descriptor=PluginDescriptor [pluginId=GoogleFitCSVImporter, pluginClass=de.opendiabetes.vault.plugin.importer.googlefit.GoogleFitCSVImporter, version=0.0.1, provider=OpenDiabetes, dependencies=[], description=, requires=*, license=null], pluginPath=export\GoogleFitCSVImporter-0.0.1.jar]' for plugin 'export\GoogleFitCSVImporter-0.0.1.jar'
2018-01-21 16:38:38,650 DEBUG org.pf4j.DependencyResolver - Graph: 
   GoogleFitCSVImporter -> []
2018-01-21 16:38:38,650 DEBUG org.pf4j.DependencyResolver - Plugins order: [GoogleFitCSVImporter]
2018-01-21 16:38:38,651 INFO org.pf4j.AbstractPluginManager - Plugin 'GoogleFitCSVImporter@0.0.1' resolved
2018-01-21 16:38:38,655 INFO org.pf4j.AbstractPluginManager - Start plugin 'GoogleFitCSVImporter@0.0.1'
2018-01-21 16:38:38,656 DEBUG org.pf4j.DefaultExtensionFactory - Create instance for plugin 'de.opendiabetes.vault.plugin.importer.googlefit.GoogleFitCSVImporter'
2018-01-21 16:38:38,656 TRACE org.pf4j.PluginClassLoader - Received request to load class 'de.opendiabetes.vault.plugin.importer.googlefit.GoogleFitCSVImporter'
2018-01-21 16:38:38,656 TRACE org.pf4j.PluginClassLoader - Search in dependencies for class 'de.opendiabetes.vault.plugin.importer.googlefit.GoogleFitCSVImporter'
2018-01-21 16:38:38,656 TRACE org.pf4j.PluginClassLoader - Couldn't find class 'de.opendiabetes.vault.plugin.importer.googlefit.GoogleFitCSVImporter' in plugin classpath. Delegating to parent
2018-01-21 16:38:38,657 ERROR org.pf4j.DefaultExtensionFactory - de.opendiabetes.vault.plugin.importer.googlefit.GoogleFitCSVImporter
java.lang.ClassNotFoundException: de.opendiabetes.vault.plugin.importer.googlefit.GoogleFitCSVImporter
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_151]
	at org.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:115) ~[pf4j-2.1.0.jar:2.1.0]
	at org.pf4j.DefaultPluginFactory.create(DefaultPluginFactory.java:46) [pf4j-2.1.0.jar:2.1.0]
	at org.pf4j.PluginWrapper.getPlugin(PluginWrapper.java:78) [pf4j-2.1.0.jar:2.1.0]
	at org.pf4j.AbstractPluginManager.startPlugin(AbstractPluginManager.java:369) [pf4j-2.1.0.jar:2.1.0]
	at de.opendiabetes.tests.plugin.importer.TestImporterUtil.getImporter(TestImporterUtil.java:22) [OpenDiabetes/:?]
	at de.opendiabetes.tests.plugin.importer.GoogleFitCSVImporterTest.setGetPath(GoogleFitCSVImporterTest.java:81) [OpenDiabetes/:?]

java.lang.NullPointerException
	at org.pf4j.AbstractPluginManager.startPlugin(AbstractPluginManager.java:369)
	at de.opendiabetes.tests.plugin.importer.TestImporterUtil.getImporter(TestImporterUtil.java:22)
	at de.opendiabetes.tests.plugin.importer.GoogleFitCSVImporterTest.setGetPath(GoogleFitCSVImporterTest.java:81)
```

Obviously the problem is '2018-01-21 16:38:38,656 TRACE org.pf4j.PluginClassLoader - Couldn't find class 'de.opendiabetes.vault.plugin.importer.googlefit.GoogleFitCSVImporter' in plugin classpath. Delegating to parent'.

The class is present within the classes folder so I don't see where the error lies.

Any help would be appreciated.

**Comment by decebals** [comment]
It's important to show us the app classpath. Be sure that the plugin jar is not present also in the app classpath.

**Comment by decebals** [comment]
Also try to use "development" mode when you run application to have more information in the log.
Other question: Do you launch your application from command line or IDE?

**Comment by lucasbuschlinger** [comment]
![image](https://user-images.githubusercontent.com/33268715/35198146-c28e2a8e-feea-11e7-9fc3-fdb2a37b32dd.png)

This is the app classpath.
This happens both when running an ant task or running from within Intellij IDEA.

And by the way: This all works flawlessly when packing the plugins as zip (and using plugin.properties)

I'll let it run in development mode and get back to you asap

**Comment by lucasbuschlinger** [comment]
Running in development mode yields the same log

**Comment by decebals** [comment]
I see an error message in log:
```
2018-01-21 16:38:38,642 ERROR org.pf4j.CompoundPluginDescriptorFinder - C:\export\GoogleFitCSVImporter-0.0.1.jar
```

The source should be https://github.com/decebals/pf4j/blob/master/pf4j/src/main/java/org/pf4j/CompoundPluginDescriptorFinder.java#L71. 
The error message is useless. Can you put a breakpoint in your IDE and see the nature of exception?

**Comment by lucasbuschlinger** [comment]
![image](https://user-images.githubusercontent.com/33268715/35242282-69011736-ffb9-11e7-87fe-ab42cbc05263.png)

Looks like the path gets somewhat mixed up and ends up being the path from root (C:\) and not relative to where the project lies.

**Comment by decebals** [comment]
I took a look to your project and I trying to find where you instantiate the PluginManager and with what settings (https://github.com/lucasbuschlinger/BachelorPraktikum/search?utf8=%E2%9C%93&q=DefaultPluginManager&type=).
Your project structure is not so clear for me (it's not clear where you keep app and plugins). Also, the way you use PF4J is a little bit uncommon (`export` directory as plugins root). 

To make some progress on this issue please try to replicate the problem on the `demo` project (from demo directory) supplied by me. 
Thanks for understanding!

**Comment by decebals** [comment]
Did you resolve the problem? Can we close this issue?

**Comment by lucasbuschlinger** [comment]
Hi sorry for not closing, we decided to stick with ZIPs for now

**Comment by decebals** [comment]
@lucasbuschlinger Thanks!
I do some research to improve and simplify the JAR support.
