### ISSUE TITLE
not find META-INF/extensions.idx

### ISSUE THREAD

**Issue by melin** [decebals/pf4j#21]
Exception in thread "main" java.lang.NullPointerException
	at ro.fortsoft.pf4j.DefaultExtensionFinder.readPluginsIndexFiles(DefaultExtensionFinder.java:176)
	at ro.fortsoft.pf4j.DefaultExtensionFinder.readIndexFiles(DefaultExtensionFinder.java:132)
	at ro.fortsoft.pf4j.DefaultExtensionFinder.find(DefaultExtensionFinder.java:54)
	at ro.fortsoft.pf4j.DefaultPluginManager.getExtensions(DefaultPluginManager.java:559)

**Comment by codespelunker** [comment]
Any chance a production release will be made available soon with this fix in it?

**Comment by decebals** [comment]
I don't understand you. Do you have the same problem? If your response is yes, please give me more details about the context when this appears.

**Comment by decebals** [comment]
Do you use the last pf4j version?

**Comment by codespelunker** [comment]
Sorry, I didn't get a notification that you had replied.  Apologies for the delay.

Yes, with the latest p4fj release, release-0.9.0 (on 7/30/14), we saw this same problem.  Getting the latest from master solved the issue for us.  I was simply wondering if you were going to make a new release.

**Comment by decebals** [comment]
Sure. Monday I will release 0.9.1

**Comment by gearlles** [comment]
I have the same problem. Are you going to release the fix soon?

**Comment by decebals** [comment]
Please check the [SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/ro/fortsoft/pf4j/pf4j/0.10.0-SNAPSHOT/). If everything is OK I will release a new version.
