### ISSUE TITLE
java.nio.file.FileSystemAlreadyExistsException

### ISSUE THREAD

**Issue by tarkal** [decebals/pf4j#96]
I have the following method that I am using to invoke a specific extension from a specific plugin:

```
public DispatchServices invokeDispatcher(Plugin plugin, Extension extension) throws MissingResourceException{

        PluginInvoker invoker = (plugin1, extension1) -> {

            // Load the plugins
            File userPluginFile = new File(AppConfig.getInstance().getUserPluginDir(plugin1.getOwner().getId()));
            PluginManager pluginManager = new DefaultPluginManager(userPluginFile);
            pluginManager.loadPlugins();

            if (plugin1.getStatus().equals(Plugin.State.ACTIVE)) pluginManager.startPlugin(plugin1.getName());

            List<DispatchServices> extensions = pluginManager.getExtensions(DispatchServices.class);
            for (DispatchServices ext : extensions) {
                if (ext.getClass().getName().equals(extension1.getImplementation())) {
                    return ext;
                }
            }
            throw new MissingResourceException("Could not invoke plugin extension.", plugin1.getName(), extension1.getName());
        };

        return (DispatchServices) invoker.invoke(plugin, extension);
    }
```

The first time this method is called everything works perfectly. However, subsequent calls to the method generate the following exception:

```
Caused by: java.nio.file.FileSystemAlreadyExistsException: null
	at com.sun.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:113) ~[zipfs.jar:1.8.0]
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:326) ~[na:1.8.0]
	at java.nio.file.FileSystems.newFileSystem(FileSystems.java:276) ~[na:1.8.0]
	at ro.fortsoft.pf4j.ServiceProviderExtensionFinder.readClasspathStorages(ServiceProviderExtensionFinder.java:70) ~[pf4j-0.12.0.jar:0.12.0]
	at ro.fortsoft.pf4j.AbstractExtensionFinder.readStorages(AbstractExtensionFinder.java:123) ~[pf4j-0.12.0.jar:0.12.0]
	at ro.fortsoft.pf4j.AbstractExtensionFinder.getEntries(AbstractExtensionFinder.java:131) ~[pf4j-0.12.0.jar:0.12.0]
	at ro.fortsoft.pf4j.AbstractExtensionFinder.find(AbstractExtensionFinder.java:49) ~[pf4j-0.12.0.jar:0.12.0]
	at ro.fortsoft.pf4j.DefaultExtensionFinder.find(DefaultExtensionFinder.java:41) ~[pf4j-0.12.0.jar:0.12.0]
	at ro.fortsoft.pf4j.DefaultPluginManager.getExtensions(DefaultPluginManager.java:555) ~[pf4j-0.12.0.jar:0.12.0]
	at co.ff36.halo.core.plugin.invoker.LocalPluginInvoker.lambda$invokeDispatcher$3(LocalPluginInvoker.java:55) ~[classes/:na]
	at co.ff36.halo.core.plugin.invoker.LocalPluginInvoker$$Lambda$4/1765003256.invoke(Unknown Source) ~[na:na]
	at co.ff36.halo.core.plugin.invoker.LocalPluginInvoker.invokeDispatcher(LocalPluginInvoker.java:66) ~[classes/:na]
	at co.ff36.halo.core.resource.server.impl.DispatcherProtocolsServerResource.represent(DispatcherProtocolsServerResource.java:55) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0]
	at org.restlet.resource.ServerResource.doHandle(ServerResource.java:523) ~[org.restlet-2.3.6.jar:na]
	... 51 common frames omitted
```

Unfortunately the stack is not overly useful in diagnosing the problem.

**Comment by decebals** [comment]
Maybe it's similar with #91. Please try the SNAPSHOT version (or try to compile the current sources) and tell me if the problem persist.

**Comment by tarkal** [comment]
Unfortunately with 0.13.0-SNAPSHOT the issue persists. The line in my code that triggers the exception is:
`List<DispatchServices> extensions = pluginManager.getExtensions(DispatchServices.class);`

Which in turn can be traced back to the `ServiceProviderExtensionFinder.readClasspathStorages()`, line 55 `FileSystem entry = FileSystems.newFileSystem(e.toURI(), Collections.emptyMap());`.

**Comment by tarkal** [comment]
Looking through the API (https://docs.oracle.com/javase/7/docs/api/java/nio/file/FileSystems.html) it states the following:

```
public static FileSystem newFileSystem(URI uri,
                       Map<String,?> env)
                                throws IOException
Constructs a new file system that is identified by a URI
This method iterates over the installed providers to locate the provider that is identified by the URI scheme of the given URI. URI schemes are compared without regard to case. The exact form of the URI is highly provider dependent. If found, the provider's newFileSystem(URI,Map) method is invoked to construct the new file system.

Once a file system is closed it is provider-dependent if the provider allows a new file system to be created with the same URI as a file system it previously created.

Usage Example: Suppose there is a provider identified by the scheme "memory" installed:

   Map<String,String> env = new HashMap<>();
   env.put("capacity", "16G");
   env.put("blockSize", "4k");
   FileSystem fs = FileSystems.newFileSystem(URI.create("memory:///?name=logfs"), env);
 
Parameters:
uri - the URI identifying the file system
env - a map of provider specific properties to configure the file system; may be empty
Returns:
a new file system
Throws:
IllegalArgumentException - if the pre-conditions for the uri parameter are not met, or the env parameter does not contain properties required by the provider, or a property value is invalid
FileSystemAlreadyExistsException - if the file system has already been created
ProviderNotFoundException - if a provider supporting the URI scheme is not installed
IOException - if an I/O error occurs creating the file system
SecurityException - if a security manager is installed and it denies an unspecified permission required by the file system provider implementation
```

There also seems to be a `getFileSystem()` method:
```
public static FileSystem getFileSystem(URI uri)
Returns a reference to an existing FileSystem.
This method iterates over the installed providers to locate the provider that is identified by the URI scheme of the given URI. URI schemes are compared without regard to case. The exact form of the URI is highly provider dependent. If found, the provider's getFileSystem method is invoked to obtain a reference to the FileSystem.

Once a file system created by this provider is closed it is provider-dependent if this method returns a reference to the closed file system or throws FileSystemNotFoundException. If the provider allows a new file system to be created with the same URI as a file system it previously created then this method throws the exception if invoked after the file system is closed (and before a new instance is created by the newFileSystem method).

If a security manager is installed then a provider implementation may require to check a permission before returning a reference to an existing file system. In the case of the default file system, no permission check is required.

Throws:
IllegalArgumentException - if the pre-conditions for the uri parameter are not met
FileSystemNotFoundException - if the file system, identified by the URI, does not exist
ProviderNotFoundException - if a provider supporting the URI scheme is not installed
SecurityException - if a security manager is installed and it denies an unspecified permission
```

I am not familiar with how the FileSystem is managed internally but the above docs are very clear as to why I am able to run the method the first time but subsequent calls generate the `FileSystemAlreadyExistsException` .

What do you think about adding a catch block like this:

```
...
if(e.toURI().getScheme().equals("jar")) {
    FileSystem entry;
    try {
        entry = FileSystems.newFileSystem(e.toURI(), Collections.emptyMap());
    } catch (FileSystemAlreadyExistsException e) {
        entry = FileSystems.getFileSystem(e.toURI());
    }
    i$ = entry.getPath(getExtensionsResource(), new String[0]);
} else {
    i$ = Paths.get(e.toURI());
}
...
```

**Comment by decebals** [comment]
I will take a look.

**Comment by decebals** [comment]
I want to ask you if you store the extensions in `META-INF/services/*` (ServiceProviderExtensionStorage) or in `extensions.idx` (LegacyExtensionStorage)? My idea is to disable by default the extensions mechanism based on `META-INF/services/*` introduced in the last version because my feeling is that it's not production ready (my intention is to add some unit tests).

**Comment by tarkal** [comment]
Im using the `META-INF/extensions.idx`.

**Comment by decebals** [comment]
I committed some code (I disabled `ServiceProviderExtensionFinder`) and create a new SNAPSHOT. Please try the last snapshot.

**Comment by tarkal** [comment]
Yes I can confirm that has fixed the issue.

**Comment by tarkal** [comment]
Have you got an ETA for 0.13.0? I would prefer not to use the SNAPSHOT for production.

**Comment by decebals** [comment]
I wish to make some tests related to `ServiceProvider` (`Storage` and `Finder`) and after these tests I can release a new version (maybe to the end of this week). I don't know how many people use the `ServiceProvider` storage and finder.

**Comment by decebals** [comment]
> Have you got an estimated release date for 0.13.0? I would prefer not to use the SNAPSHOT for production.

Done
